[ADD] Express 초기 환경세팅
wecode-bootcamp-korea/43-backend-westagram-2 pull request #1
Opened 2023-02-22 07:38 UTC by rkdgurwn14

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [v] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
Assignment1 | Express 초기 환경 설정

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
초기 환경 설정 후 서버의 작동과 DB와의 연동

<br />

## :: 테스트 결과 이미지
<img width="273" alt="스크린샷 2023-02-22 오후 4 37 30" src="https://user-images.githubusercontent.com/121275209/220553763-70cbf52a-6bf2-434c-ae54-1c6939d0804c.png">

<br />

## :: 기타 질문 및 특이 사항
실제로 DB와 연결이 되었다는 것을 어떻게 알 수 있나요?

2023-02-22 10:49 UTC, kyeongraekim requested changes
- 현재 누락된 파일 목록 공유드립니다.
- .env.sample
- .gitignore

2023-02-22 10:49 UTC, kyeongraekim commented on hyukju/app.js
> +dotent.config(); //dotent 라이브러리 실행
- dotent 라는 오타가 눈에 띄네요!
- 코드 독해로 충분히 이해가 가능한 부분에 불필요한 주석은, 상용화를 목적으로 main 으로 올리는 코드내에서 삭제해주세요!

2023-02-22 10:49 UTC, kyeongraekim commented on hyukju/app.js
> +  database: process.env.TYPEORM_DATABASE,
- 현재 TYPEORM_CONNECTION 등의 환경변수 네이밍은 언제 어디든지 typeORM을 제외한 다양한 ORM 라이브러리와 연동될 수 있는 mysql의 환경 변수 용례를 극히 제한하는 모습처럼 보여집니다.
- 따라서 DB_CONNECTION, DB_HOST 등의 워딩으로 바꿔주시면 더 좋을 것 같아보입니다!
- 또한 환경변수의 밸류값은 샘플링을 위한 데이터임으로, 가장 포괄적인 내용으로 바꾸어주세요! chang, library는 실제 사용할 수 있을법한 혹은 과거에 사용했을법한 이름들이네요!

2023-02-22 10:49 UTC, kyeongraekim commented on hyukju/app.js
> +const { DataSource } = require(`typeorm`);
- import 순서 컨벤션에 맞게 수정해주세요! 사소한 부분이라 놓치기 쉽지만 처음 코드를 작성할 때부터 신경쓰고 작성하게 되면 추후에 관리하기도 용이하며 가독성도 좋아집니다.

- 다음과 같은 순서로 import 해줍니다.
Bulit-in 패키지
3rd-party 패키지
custom 패키지

  ```javascript
  //// Built-in package
  const http = require('http')
  
  //// 3rd-party package
  require('dotenv').config();
  const express = require('express');
  const cors    = require('cors');
  const morgan  = require('morgan');
  const { DataSource } = require('typeorm');
  
  //custom package
  const api = require('./../api')
  
  const app = express();

2023-02-23 01:59 UTC, kyeongraekim requested changes

2023-02-23 01:59 UTC, kyeongraekim commented on hyukju/.env.sample
> +TYPEORM_LOGGING = TRUE
- 해당 환경변수의 키값에 대한 워딩변경 수정이 반영이 안되어있네요!
- DB_CONNECTION 등으로 TYPEORM_의 앞단어들을 변경해야하는 당위성을 앞선 리뷰에 달아드렸으니 확인해주세요!

2023-02-23 01:59 UTC, kyeongraekim commented on hyukju/.gitignore
> +
- 추후에 db/schema.sql 이 올라오지 않게 추가해줄 필요가 있어보이네요!

2023-02-23 02:14 UTC, rkdgurwn14 commented on hyukju/.gitignore
> +
.gitignore에 /tests/_output/* !/tests/_output/.gitkeep 가 있는데 
혹시 db/schema.sql 이 올라오지 않게 하려면 어떻게 해야 할까요?

2023-02-23 07:13 UTC, rkdgurwn14 commented
과제 1번 내용만 올려야 했는데 과제 2를 하다가 과제 2 내용까지 올려버렸습니다!

2023-02-23 08:03 UTC, kyeongraekim requested changes

2023-02-23 08:03 UTC, kyeongraekim commented on hyukju/app.js
> +const dotenv = require("dotenv"); //require("dotenv") .config()
- 불필요한 주석을 삭제해주세요!

2023-02-23 08:03 UTC, kyeongraekim commented on hyukju/app.js
> +  //my를 지우기
- 불필요한 주석을 삭제해주세요!

2023-02-23 08:03 UTC, kyeongraekim commented on hyukju/app.js
> +
- 해당 내용은 두 번 째 과제 푸시 브랜치에 녹여져 들어가야 하는 내용입니다. 관련하여 해당 내용은 제외한 내용이 올라 올 수 있게 브랜치 내 코드를 재조정해주세요!
- 해당 코드를 잠시 삭제하고 add commit 후 푸시한는 방법이 제일 간단하겠네요!

2023-02-23 08:03 UTC, kyeongraekim commented on hyukju/db/migrations/20230223060233_likes.sql
> +);
- 중복의 좋아요 데이터 기입을 막을 수 있게 SQL 문법 중 UNIQUE CONSTRAINT 제한을 걸어주세요!

2023-02-23 08:03 UTC, kyeongraekim commented on hyukju/db/schema.sql
> +/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
- schema.sql 파일이 여전히 올라오고 있네요!

2023-02-23 08:48 UTC, closed without merging