[임수정] Assignment 3: Express API - CRUD
wecode-bootcamp-korea/43-backend-westagram-2 pull request #11
Opened 2023-02-27 06:16 UTC by trtw9889

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- CRUD 작업을 통해 API 만들기

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- CRUD기능구현을 통해 API 만들기

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
3. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
-posts 데이터베이스 수정을 하였습니다. 참고해주세요

2023-02-27 08:12 UTC, Jon9Beom commented on sujeong/app.js
> +    }
- 비동기 처리를 하는 방법은 크게 callback, promise, async/await를 사용하는 방법이 있는데, 작성하신 코드에서는 이를 혼합해서 사용하고 있습니다. 아래 예제를 참고해서 리펙토링해주세요.
- 가능하다면 이전 문법인 콜백함수 대신, async await를 활용해서 수정해주세요~
    
    ```jsx
    // Bad
    app.get("/posts", async (req, res) => {
        await myDataSource.manager.query(
            `SELECT 
                u.id AS userId,
                u.profile_Image AS userProfileImage,
                p.id AS postingId,
                p.title AS postingTitle,
                p.content AS postingContent
            FROM users u
            INNER JOIN posts p ON
            u.id = p.user_id
            `,
            (err, rows) => {
                res.status(200).json({ data: rows });
            }
        );
    });
    
    // Good - callback 방식의 비동기처리
    app.get("/posts", (req, res) => {
        myDataSource.query(`SELECT * FROM users`,
          // 비동기 처리 이후에 실행되는 callback
          (err, data) => {res.status(200).json({ data: data })}
        );
    });
    
    // Good - async와 await 방식의 비동기처리
    app.get("/posts", async(req, res) => {
      const users = await myDataSource.query(`SELECT * FROM users`);
      
      res.status(200).json({ data : users})
    });
    
    ```

2023-02-27 08:12 UTC, Jon9Beom commented on sujeong/app.js
> +app.get("/posting_search/:userId", async (req, res) => {
수정님 해당 API는 users 중, 특정 user의, posts 목록들을 가져오는 API이지요?
이런 경우에는 `/` 를 통해 계층 관계를 표현하면 조금 더 읽기 쉬운 엔드포인트가 될 수 있습니다.

위의 문구에서 `,`를 기준으로 나눠 말씀 드린 것 처럼 작성 한다면, 조금 더 쉽게 이해하실 수 있습니다.

```
# CASE 1. /users/:userId/posts
http -v GET localhost:3000/users/1/posts    # 서버의 유저들 중, 1번 유저의, 게시글들을 get(가져오는) 엔드포인트

# CASE 2./posting_search/:userId
http -v GET localhost:3000/posting_search/1          # 내가 의도한 건 CASE 1과 같지만 실제로 읽어지기로는 서버의 포스팅을 검색하겠다는건데 뒤의 숫자 1이 정확히 뭘 의미하는건지 파악하기 힘듦
```
차이가 조금 느껴지시나요?

이렇듯 자명한(그 자체만으로도 설명이 되는) 엔드포인트를 RESTful 하게 설계된 엔드포인트이자 API라고 말하는데, 이는 앞으로 있을 RESTful API 세션을 통해 한 번 더 자세하게 짚고 배워볼 예정이니, '이런식으로 엔드포인트를 작성하면 되는구나~' 라는 느낌만 가져가시면 될 것 같아요!

수정 부탁드립니다 :)

2023-02-27 08:12 UTC, Jon9Beom commented on sujeong/app.js
> +app.post("/posting_likes", async (req, res) => {
- 좋아요 기능을 구현할 때에는 주의해야할 점이 있습니다.
- 하나의 사용자가 하나의 게시물에 대해서 좋아요를 할 수 있는 횟수는 단 한 번 이어야 합니다.
- 지금 구조에서는 좋아요를 누를 때마다 아래와 같이 likes 테이블에 계속해서 중복으로 데이터가 저장됩니다.
    
    ```sql
    +----+---------+---------+---------------------+
    | id | user_id | post_id | created_at          |
    +----+---------+---------+---------------------+
    |  1 |       1 |       3 | 2022-07-16 14:18:26 |
    |  2 |       1 |       3 | 2022-07-16 14:18:26 |
    |  3 |       1 |       3 | 2022-07-16 14:18:26 |
    |  4 |       1 |       3 | 2022-07-16 14:18:26 |
    |  5 |       1 |       3 | 2022-07-16 14:18:47 |
    |  6 |       1 |       3 | 2022-07-16 14:18:47 |
    +----+---------+---------+---------------------+
    ```
    
- 이를 막기 위해서, likes 테이블에 user_id와 post_id를 기준으로 UNIQUE 제약조건을 추가하는 migration 파일을 추가로 만들어서 올려주세요.

2023-02-28 07:06 UTC, Kang-kyunghun requested changes

2023-02-28 07:06 UTC, Kang-kyunghun commented on sujeong/app.js
> +});
1. 변수명은 최대한 어떠한 데이터가 담겨있는지를 표시해주는 것이 좋습니다.
2. post라는 변수를 배열로 감쌌는데, 이렇게하면 post라는 변수에 결과로 올 배열의 첫번째 값이 post 변수에 담깁닌다. 그래서 마지막에 post[0]처럼 인데스를 안 사용할 수 있습니다.
3. status code 201은 데이터가 생성 될 때 사용하므로 200으로 수정해 주면 좋을 것 같습니다.
```suggestion
  const [post] = await appDataSource.query(
    `SELECT
      u.id AS userId,
      u.name AS userName,
      p.id AS postingId,
      p.title AS postingTitle,
      p.content AS postingContent
      FROM posts AS p
      JOIN users AS u ON p.user_id=u.id
      WHERE p.id=?
      `,
    [postId]
  );
  res.status(200).json({ data:post });
});
```

2023-02-28 07:06 UTC, Kang-kyunghun commented on sujeong/app.js
> +const { DataSource, AbstractRepository, And } = require("typeorm");
AbstractRepository, And 해당 모듈을 사용하지 않을 것 같은데, 제거해 주세요.

```suggestion
const { DataSource } = require("typeorm");
```

2023-03-02 02:32 UTC, merged