[임수정] Assignment 1: Express API - 초기 환경 세팅
wecode-bootcamp-korea/43-backend-westagram-2 pull request #2
Opened 2023-02-22 09:18 UTC by trtw9889

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- express를 활용한 API기초세팅
<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- cors,.env 등을 이용한 API 기초세팅설정 완료

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
   
![스크린샷 2023-02-22 오후 6 12 39](https://user-images.githubusercontent.com/122195011/220574932-781bc8fb-70da-453c-a0f5-134522d4e2c6.png)

2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지

<img width="1271" alt="스크린샷 2023-02-22 오후 6 14 20" src="https://user-images.githubusercontent.com/122195011/220575116-e9ded4d5-9437-40f1-bac2-d96d6ed4e871.png">

3. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

![스크린샷 2023-02-22 오후 6 17 28](https://user-images.githubusercontent.com/122195011/220575906-9bbc56bf-d3b6-4527-8681-ea7211700ef3.png)

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-02-22 10:43 UTC, kyeongraekim requested changes

2023-02-22 10:43 UTC, kyeongraekim commented on sujeong/db/schema.sql
> +) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
- 다음의 링크를 확인해주세요! 해당 데이터베이스를 만들 때, utf8mb4_general_ci 등의 세팅을 create table 시 명령어로 맞게 입력하셨는지 확인 부탁드립니다! [링크 바로가기](https://rastalion.me/mysql-8-0-1-%EB%B2%84%EC%A0%84%EB%B6%80%ED%84%B0-%EC%B1%84%ED%83%9D%EB%90%9C-utf8mb4_0900_ai_ci%EC%9D%98-%ED%95%9C%EA%B8%80-%EC%82%AC%EC%9A%A9%EC%97%90-%EB%8C%80%ED%95%9C-%EB%AC%B8%EC%A0%9C%EC%A0%90/)

2023-02-22 10:43 UTC, kyeongraekim commented on sujeong/.env.sample
> +TYPEORM_LOGGING = YOUR LOGGING
- 현재 TYPEORM_CONNECTION 등의 환경변수 네이밍은 언제 어디든지 typeORM을 제외한 다양한 ORM 라이브러리와 연동될 수 있는 mysql의 환경 변수 용례를 극히 제한하는 모습처럼 보여집니다.
- 따라서 DB_CONNECTION, DB_HOST 등의 워딩으로 바꿔주시면 더 좋을 것 같아보입니다!
- 또한 환경변수의 밸류값은 샘플링을 위한 데이터임으로, 가장 포괄적인 내용으로 바꾸어주세요! chang, library는 실제 사용할 수 있을법한 혹은 과거에 사용했을법한 이름들이네요!

2023-02-22 10:43 UTC, kyeongraekim commented on sujeong/app.js
> +myDataSource.initialize().then(() => {
- 추가로 DataSource.initialize() 함수가 실행되고 나면, then()과 catch()를 사용해서 에러를 핸들링해줄 수 있습니다. 이렇게 하면, initialize() 함수가 실행되어서 database와 실제로 connection을 생성할 때, 성공했는지 실패했는지 여부를 확인할 수 있습니다.

2023-02-22 10:43 UTC, kyeongraekim commented on sujeong/app.js
> +
- import 순서 컨벤션에 맞게 수정해주세요! 사소한 부분이라 놓치기 쉽지만 처음 코드를 작성할 때부터 신경쓰고 작성하게 되면 추후에 관리하기도 용이하며 가독성도 좋아집니다.

- 다음과 같은 순서로 import 해줍니다.
Bulit-in 패키지
3rd-party 패키지
custom 패키지

  ```javascript
  //// Built-in package
  const http = require('http')
  
  //// 3rd-party package
  require('dotenv').config();
  const express = require('express');
  const cors    = require('cors');
  const morgan  = require('morgan');
  const { DataSource } = require('typeorm');
  
  //custom package
  const api = require('./../api')
  
  const app = express();
  ```

2023-02-22 10:43 UTC, kyeongraekim commented on sujeong/db/schema.sql
> +/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
- 추가로 해당 schema.sql 파일은 개인 로컬환경에 특수성이 가미되어 자동으로 작성되는 파일임으로, 제 3자와 함께 파일과 코드를 공유 하는 깃헙 환경에는 공유가 되어서는 안됩니다! 참고해주세요!~

2023-02-23 05:20 UTC, Kang-kyunghun commented
LGTM!

2023-02-23 05:20 UTC, merged