Feature/wonsik join - [ADD] Assignment 2 | 유저 회원가입 하기
wecode-bootcamp-korea/43-backend-westagram-2 pull request #6
Opened 2023-02-23 07:06 UTC by Choiwonsikk

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- API 호출 시 필요한 값들에 대한 유효성 검사 (예시)

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
![image](https://user-images.githubusercontent.com/121328277/220839818-00abd172-3ff1-4c30-98a7-77c015dfb8b5.png)

2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/121328277/220839958-da15c32f-0599-49f0-b1dd-c5605139b32e.png">

3. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지
![image](https://user-images.githubusercontent.com/121328277/220840105-5f8a8278-5f05-4f7a-9e70-5c69ddcae9d6.png)

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-02-23 08:07 UTC, kyeongraekim requested changes

2023-02-23 08:07 UTC, kyeongraekim commented on wonsik/app.js
> +app.post("/users", async (req, res, next) => {
- 현재 내부 코드에서 next는 메소드로 활용되어있지 않고 있네요! 해당 내용은 삭제해주셔도 좋을 것  같아요!~

2023-02-23 08:07 UTC, kyeongraekim commented on wonsik/app.js
> +  const { name, email, profile_image, password } = req.body;
- javascript의 기본 변수 네이밍 컨벤션은 snake_case 가 아닌, camelCase 입니다. 해당 내용 참고하여 수정해주세요!

2023-02-23 08:07 UTC, kyeongraekim commented on wonsik/db/migrations/20230223055055_create_users_table.sql
> +    email VARCHAR(200) NULL,
- 이메일의 중복 가입을 막는 unique 설정을 추가해주세요!

2023-02-23 08:07 UTC, kyeongraekim commented on wonsik/db/migrations/20230223055128_create_likes_table.sql
> +);
- like 좋아요의 중복 데이터 기입을 막을 수 있게 unique 설정을 추가해주세요!

2023-02-24 02:10 UTC, kyeongraekim requested changes

2023-02-24 02:10 UTC, kyeongraekim commented on wonsik/db/migrations/20230223055128_create_likes_table.sql
> +    post_id INT UNIQUE NOT NULL,
- 해당 설정은, user_id의 중복을 막기 때문에 1번 유저는 단 한 건의 post에만 좋아요를 누를 수 밖에 없게 됩니다.
- 다시 말해, likes table에 user_id가 1인 데이터는 단 한 건만 들어오는 설정이 되어 있습니다.
- Unique 설정을 (user_id, post_id) 두 건을 동시에 적용하는 방법을 한 번 고민해주세요!

2023-02-24 02:10 UTC, kyeongraekim commented on wonsik/db/migrations/20230223055128_create_likes_table.sql
> +    post_id INT UNIQUE NOT NULL,
- 다음의 링크를 참고해주세요! [링크 바로가기](https://www.w3schools.com/sql/sql_unique.asp)

2023-02-24 06:21 UTC, Choiwonsikk commented on wonsik/db/migrations/20230223055128_create_likes_table.sql
> +    post_id INT UNIQUE NOT NULL,
감사합니다

2023-02-27 05:42 UTC, kyeongraekim requested changes

2023-02-27 05:42 UTC, kyeongraekim commented on wonsik/app.js
> +app.use(cors()); // 데이터 통신 도움
불필요한 주석 제거해주세요!

2023-02-27 05:42 UTC, kyeongraekim commented on wonsik/db/migrations/20230223055128_create_likes_table.sql
> +user_id INT  NOT NULL,
indentation 한번만 더 신경써주세요!

2023-02-27 07:13 UTC, Jon9Beom commented
LGTM 👍

2023-02-27 07:13 UTC, merged